name: Build backend

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
          envkey_JWT_ACCESS_TOKEN_SECRET: 'secret'
          envkey_JWT_VERIFICATION_TOKEN_SECRET: 'secret'
          envkey_JWT_REFRESH_TOKEN_SECRET: 'secret'
          envkey_JWT_ACCESS_TOKEN_EXPIRATION_TIME: 7200
          envkey_JWT_REFRESH_TOKEN_EXPIRATION_TIME: 3600
          file_name: .env.development
          fail_on_empty: true

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: install --ignore-engines

      - name: Build project
        uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: Run tests
        uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: test --detectOpenHandles
