name: Build backend

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: NPM Ci
        run: npm ci

      - name: NPM EsLint check
        run: 
          npm run lint

      - name: NPM Build
        run: 
          npm run build

      - name: NPM Test
        run: npm run test